from src.engine.index import collect_messages, get_completion_summary, format_conversation_history, extract_confidence
from src.engine.prompts import get_summary_prompt

collect_messages = collect_messages
get_completion_summary = get_completion_summary
format_conversation_history = format_conversation_history
extract_confidence = extract_confidence
get_summary_prompt = get_summary_prompt